name: gestor_herramientas
description: Gestor de herramientas en Flutter.
publish_to: "none"
version: 1.4.0+4

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_quill: ^11.6.0
  sqflite: ^2.4.2
  path: ^1.9.1
  image_picker: ^1.1.2
  path_provider: ^2.1.5
  archive: ^4.0.7
  file_picker: ^10.3.3
  share_plus: ^10.1.4
  cross_file: ^0.3.4+2
  flutter_svg: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  sqflite_common_ffi: ">=2.3.7 <2.4.0"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/herramientas.png
    - assets/icons/electricos/
