name: gestor_richtext_flutter
description: Prueba de editor enriquecido para el gestor de herramientas.
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_quill: ^11.6.0
  sqflite: ^2.4.4
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
